名字: Update NY Times RSS
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - run: pip install feedparser feedgenerator requests
      - run: python nytimes.py
      - run: |
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add nytimes.xml
          git commit -m "auto update"
          git push
